globals:
  datasetBaseUrl: env:DATASET_BASE_URL

middlewares:
  static-assets:
    module: trifid-core/middlewares/static.js
    order: 0
    paths: /static-assets
    config:
      directory: file:static

  rewrite:
    module: trifid-core/middlewares/rewrite.js

  welcome:
    module: trifid-core/middlewares/view.js
    paths: /
    methods: GET
    config:
      path: file:welcome.hbs

  entity-renderer:
    module: "@zazuko/trifid-renderer-entity"

  fetch-handler:
    module: trifid-handler-fetch
    config:
      url: env:FETCH_HANDLER_FILE
      contentType: env:FETCH_HANDLER_FILE_TYPE
      split: true
      cache: true
