# server:
#   logLevel: debug

globals:
  datasetBaseUrl: env:DATASET_BASE_URL
  sparqlEndpoint:
    url: env:SPARQL_ENDPOINT_URL
    username: env:SPARQL_ENDPOINT_USERNAME
    password: env:SPARQL_ENDPOINT_PASSWORD

middlewares:
  static-assets:
    module: trifid-core/middlewares/static.js
    order: 0
    paths: /static-assets
    config:
      directory: file:static

  welcome:
    module: trifid-core/middlewares/view.js
    paths: /
    methods: GET
    config:
      path: file:welcome.hbs

  entity-renderer:
    module: "@zazuko/trifid-entity-renderer"
    config:
      labelLoader:
        chunkSize: 30
        concurrency: 2
        timeout: 4000

  yasgui:
    module: trifid-plugin-yasgui
    paths: /sparql
    config:
      urlShortener: https://s.zazuko.com/api/v1/shorten

  graph-explorer:
    module: trifid-plugin-graph-explorer
    paths: /graph-explorer

  spex:
    module: trifid-plugin-spex
    paths: /spex

  sparql-proxy:
    module: "@zazuko/trifid-plugin-sparql-proxy"
    paths: /query
    config:
      queryOperation: postQueryUrlencoded
      rewriteQueries: true
      cache:
        prefix: env:SPARQL_PROXY_CACHE_PREFIX
        url: env:SPARQL_PROXY_CACHE_URL
        clearAtStartup: env:SPARQL_PROXY_CACHE_CLEAR_AT_STARTUP

  handle-redirects:
    module: "@zazuko/trifid-handle-redirects"
