server:
  logLevel: debug

globals:
  datasetBaseUrl: http://localhost:3000/
  endpoints:
    default:
      url: /query

middlewares:
  entity-host-web-page:
    module: trifid-core/middlewares/view.js
    paths: /
    config:
      path: file:../views/welcome.hbs

  yasgui:
    module: trifid-plugin-yasgui
    paths: /sparql

  fetch-handler:
    module: trifid-handler-fetch
    paths: /query
    config:
      url: file:../data/people.ttl
      contentType: text/turtle
      baseIRI: http://example.com
      graphName: http://example.com/graph
      unionDefaultGraph: true
