# yaml-language-server: $schema=../../../core/lib/config/schema.json

server:
  logLevel: debug
  logFormat: pretty

globals:
  datasetBaseUrl: http://localhost:3000/
  endpoints:
    default:
      url: /query

plugins:
  welcome-page:
    module: trifid-core/plugins/view.js
    paths: /
    config:
      path: file:../views/welcome.hbs

  yasgui:
    module: trifid-plugin-yasgui
    paths:
      - /sparql
      - /sparql/

  fetch-handler:
    module: trifid-handler-fetch
    paths: /query
    config:
      url: file:../data/data.ttl
      contentType: text/turtle
      baseIRI: http://example.com
      graphName: http://example.com/graph
      unionDefaultGraph: true
