server:
  logLevel: debug

middlewares:
  entity-host-web-page:
    module: trifid-core/middlewares/view.js
    paths: /
    methods: GET
    config:
      path: file:../views/welcome.hbs

  yasgui:
    module: trifid-plugin-yasgui
    paths: /sparql

  fetch-handler:
    module: trifid-handler-fetch
    paths: /query
    config:
      url: file:../data/people.ttl
      contentType: text/turtle
      baseIRI: http://example.com
      graphName: http://example.com/graph

  sparql-handler:
    module: trifid-handler-sparql
    config:
      resourceExistsQuery: "ASK { GRAPH ?g { <${iri}> ?p ?o }}"
      resourceGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <${iri}>"
      containerExistsQuery: "ASK { GRAPH ?g { <${iri}> ?p ?o }}"
      containerGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <${iri}>"
