# This loads the TBBT dataset from a remote file using the `trifid-handler-fetch` middleware.
# Start this example by running: `npm run start:tbbt`
# Example of a working URL: http://localhost:8080/data/person/amy-farrah-fowler

globals:
  datasetBaseUrl: http://localhost:8080/

middlewares:
  morgan:
    module: file:../../middlewares/morgan.js

  rewrite:
    module: trifid-core/middlewares/rewrite.js

  welcome:
    module: trifid-core/middlewares/view.js
    paths: /
    methods: GET
    config:
      path: file:welcome.hbs

  entity-renderer:
    module: "@zazuko/trifid-entity-renderer"

  fetch-handler:
    module: trifid-handler-fetch
    config:
      url: https://raw.githubusercontent.com/zazuko/tbbt-ld/master/dist/tbbt.nt
      contentType: application/n-triples
      split: true
      cache: true
