# This loads the TBBT dataset from a remote file using the `trifid-handler-fetch` middleware.
# Start this example by running: `npm run start:tbbt`
# Example of a working URL: http://localhost:8080/data/person/amy-farrah-fowler

server:
  logLevel: debug

globals:
  datasetBaseUrl: http://localhost:8080/
  endpoints:
    default:
      url: /query

middlewares:
  morgan:
    module: file:../../middlewares/morgan.js

  welcome:
    module: trifid-core/middlewares/view.js
    paths: /
    methods: GET
    config:
      path: file:welcome.hbs

  yasgui:
    module: trifid-plugin-yasgui
    paths: /sparql

  entity-renderer:
    module: "@zazuko/trifid-entity-renderer"

  fetch-handler:
    module: trifid-handler-fetch
    config:
      url: https://raw.githubusercontent.com/zazuko/tbbt-ld/master/dist/tbbt.nt
      contentType: application/n-triples
      baseIRI: http://localhost:8080
      graphName: http://example.com/graph
      unionDefaultGraph: true
