name: Run Tests

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16
          - 18

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
